# Copyright 2022 The configurer Authors. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

---
version: "2"

run:
  timeout: 1m

linters:
  default: all
  disable:
    - wrapcheck
    - testpackage
    - contextcheck
    - gochecknoglobals
    - exhaustruct
    - paralleltest
    - godox
    - cyclop
    - tagliatelle
    - err113
    - varnamelen
    - ireturn
    - exhaustive
    - dupword
    - depguard
    - testifylint
    - perfsprint
    - mnd
    - wsl
    - nlreturn
    - funlen
    - gocognit
    - noctx
    - staticcheck
    - errcheck
    - intrange
    - gosec
    - nestif
    - goconst
    - prealloc
    - lll
    - maintidx
    - gochecknoinits
    - forbidigo
    - revive

# Settings for specific linters
linters-settings:
  funlen:
    lines: 175
    statements: 80

  nestif:
    min-complexity: 8

  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude-rules:
    - path: cmd/
      linters:
        - gochecknoinits
        - mnd
        - forbidigo
        - errcheck
        - lll
        - goconst
        - intrange
        - revive

    - path: awsssm/
      linters:
        - lll

    - path: awssm/
      linters:
        - lll

    - path: example_test.go
      linters:
        - lll

    - path: github/github.go
      linters:
        - mnd

    - path: util/
      linters:
        - mnd
        - gocognit
        - gocyclo
        - funlen
        - maintidx
        - dupl
        - goconst
        - nestif

    - path: _test\.go
      linters:
        - wsl
        - nlreturn
        - funlen
        - dupl
        - gocognit
        - maintidx
        - goconst
        - lll
        - revive

    - path: doc.go
      linters:
        - lll
        - revive

    - path: parsers/
      linters:
        - revive

    - path: parser/
      linters:
        - revive

    - path: util/
      linters:
        - revive

    - path: option/
      linters:
        - revive

    - linters:
        - lll
      source: "json:"

    - linters:
        - gocritic
        - godot
      source: "//////"

    - linters:
        - gosec
      text: "G112:"
