project_name: example
builds:
  - id: linux-arm7-rpi-3
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
      - "7"
    no_unique_dist_dir: true
  - env: 
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

source:
  enabled: true

# SEE: https://shibumi.dev/posts/keyless-signatures-with-github-actions/
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output=${signature}", "${artifact}"]
    artifacts: all

checksum:
  name_template: "checksums"
