project_name: configurer
builds:
  - env: 
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

source:
  enabled: true

# SEE: https://shibumi.dev/posts/keyless-signatures-with-github-actions/
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    args: ["sign-blob", "--oidc-issuer=https://token.actions.githubusercontent.com", "--yes", "--output-signature=${signature}", "${artifact}"]
    artifacts: all

checksum:
  name_template: "checksums"
